### ISSUE TITLE
Builder with EVMJIT enabled should run JIT tests

### ISSUE THREAD

**Issue by chfast** [ethereum/ethereum-buildbot#33]
test-cpp step is a command `testeth`. To test JIT it should be `testeth --jit`. It can be added as another step (better) or test-cpp step can be modified.

**Comment by chfast** [comment]
Something went wrong with that: the command is now `./testeth -t 'devcrypto,jsonrpc,Solidity*,whisper,jit'`, should be `./testeth -t 'devcrypto,jsonrpc,Solidity*,whisper' --jit`.

**Comment by caktux** [comment]
Fixed in 39fb6a0, thanks!
